M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu20.04.1} date Sun 09 Jan 2022 06:53:23 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-09T18:53:23+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.986
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.988
%
G90
G05
T1
X86.555Y-82.1
X86.555Y-87.88
T2
X121.565Y-86.959
X121.565Y-88.991
T3
X116.485Y-87.975
T0
M30
